name: Install njinx

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  nginx:
    runs-on: ubuntu-latest
    container:
      image: node

    steps:
      - uses: actions/test@v1
      - name: Install
        run: |
          npm install
          npm test
  cd:
    runs-on: ubuntu-latest
    needs: nginx

    steps:
      - uses: actions/test@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t back .
      - name: Tags
        run: |
          docker tag back ${{ secrets.DOCKER_USER }}/back:${{ github.sha }}
          docker tag back ${{ secrets.DOCKER_USER }}/back:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/back:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/back:latest
